"""Versioned field metadata used to generate friendly configuration forms."""


def field(key, label, value, group, kind="number", **kwargs):
    return {"key": key, "label": label, "value": value, "group": group, "type": kind, **kwargs}


def boolean(key, label, value, group, description=""):
    return field(key, label, value, group, "boolean", description=description)


def number(key, label, value, group, description="", minimum=0, maximum=100, step=1):
    return field(key, label, value, group, "number", description=description, min=minimum, max=maximum, step=step)


def text(key, label, value, group, description="", password=False):
    return field(key, label, value, group, "password" if password else "text", description=description)


def select(key, label, value, options, group, description=""):
    return field(key, label, value, group, "select", options=options, description=description)


PALWORLD_FIELDS = [
    # Server management
    text("ServerName", "服务器名称", "Pal Haven", "服务器管理", "显示在服务器列表中的名称。"),
    text("ServerDescription", "服务器描述", "A private world for friends.", "服务器管理", "服务器列表中显示的说明。"),
    text("AdminPassword", "管理员密码", "", "服务器管理", "获取管理员权限时使用。", password=True),
    text("ServerPassword", "加入密码", "", "服务器管理", "玩家加入服务器时需要的密码。", password=True),
    number("ServerPlayerMaxNum", "最大玩家数", 16, "服务器管理", "允许同时加入的玩家数量。", 1, 32),
    text("PublicIP", "公共 IP", "", "服务器管理", "社区服务器对外公布的 IP；留空自动判断。"),
    number("PublicPort", "公共端口", 8211, "服务器管理", "社区列表显示端口，不改变实际监听端口。", 1, 65535),
    boolean("RCONEnabled", "启用 RCON", False, "服务器管理", "允许通过 RCON 管理服务器。"),
    number("RCONPort", "RCON 端口", 25575, "服务器管理", "RCON 监听端口。", 1, 65535),
    boolean("RESTAPIEnabled", "启用 REST API", False, "服务器管理", "启用官方 REST 管理接口。"),
    number("RESTAPIPort", "REST API 端口", 8212, "服务器管理", "REST API 监听端口。", 1, 65535),
    boolean("bAllowClientMod", "允许客户端模组", False, "服务器管理", "允许启用模组的玩家加入。"),
    boolean("bEnableBuildingPlayerUIdDisplay", "显示建筑创建者 ID", True, "服务器管理", "在建筑上显示创建者玩家 ID。"),
    boolean("bIsShowJoinLeftMessage", "显示加入离开消息", True, "服务器管理", "显示玩家加入或离开提示。"),
    boolean("bIsUseBackupSaveData", "启用世界备份", True, "服务器管理", "由游戏服务端自动保留存档备份，会增加磁盘负载。"),
    number("ChatPostLimitPerMinute", "每分钟聊天上限", 10, "服务器管理", "单个玩家每分钟可发送的消息数量。", 0, 120),
    text("CrossplayPlatforms", "跨平台列表", "(Steam,Xbox,PS5,Mac)", "服务器管理", "允许连接的平台列表。"),
    select("LogFormatType", "日志格式", "Text", ["Text", "Json"], "服务器管理", "服务端日志的输出格式。"),

    # Performance
    number("BaseCampMaxNum", "全服基地总数", 128, "性能", "服务器中允许存在的基地总数。", 1, 1000),
    number("BaseCampMaxNumInGuild", "每公会基地数", 4, "性能", "单个公会基地上限，官方建议不超过 10。", 1, 10),
    number("BaseCampWorkerMaxNum", "每基地工作帕鲁数", 15, "性能", "单个基地工作帕鲁上限，最大 50。", 1, 50),
    number("ItemContainerForceMarkDirtyInterval", "容器强制同步间隔", 1.0, "性能", "打开容器时强制重新同步的秒数。", 0.1, 60, 0.1),
    number("MaxBuildingLimitNum", "每玩家建筑上限", 0, "性能", "0 表示不限制。", 0, 100000),
    number("PhysicsActiveDropItemMaxNum", "物理掉落物上限", 3000, "性能", "可使用物理行为的掉落物最大数量。", 0, 10000),
    number("ServerReplicatePawnCullDistance", "帕鲁同步距离", 15000, "性能", "玩家周围帕鲁同步距离，单位厘米。", 5000, 15000, 100),

    # Features
    number("AutoResetGuildTimeNoOnlinePlayers", "离线公会重置时间", 72, "游戏功能", "触发离线公会清理前的离线时间。", 0, 8760, 1),
    boolean("bAutoResetGuildNoOnlinePlayers", "自动清理离线公会", False, "游戏功能", "长期无人登录时删除公会建筑与基地帕鲁。"),
    boolean("bAllowEnhanceStat_Attack", "允许强化攻击", True, "游戏功能"),
    boolean("bAllowEnhanceStat_Health", "允许强化生命", True, "游戏功能"),
    boolean("bAllowEnhanceStat_Stamina", "允许强化耐力", True, "游戏功能"),
    boolean("bAllowEnhanceStat_Weight", "允许强化负重", True, "游戏功能"),
    boolean("bAllowEnhanceStat_WorkSpeed", "允许强化工作速度", True, "游戏功能"),
    boolean("bAllowGlobalPalboxExport", "允许导出全局帕鲁终端", False, "游戏功能"),
    boolean("bAllowGlobalPalboxImport", "允许导入全局帕鲁终端", False, "游戏功能"),
    boolean("bBuildAreaLimit", "限制特殊区域建筑", True, "游戏功能", "禁止在传送点等特殊设施附近建造。"),
    boolean("bCharacterRecreateInHardcore", "硬核死亡后重建角色", False, "游戏功能"),
    boolean("bDisplayPvPItemNumOnWorldMap_BaseCamp", "地图显示基地 PvP 物品", False, "游戏功能"),
    boolean("bDisplayPvPItemNumOnWorldMap_Player", "地图显示玩家 PvP 物品", False, "游戏功能"),
    boolean("bEnableFastTravel", "启用快速传送", True, "游戏功能"),
    boolean("bEnableFastTravelOnlyBaseCamp", "仅允许基地间传送", False, "游戏功能"),
    boolean("bEnableInvaderEnemy", "启用入侵事件", True, "游戏功能"),
    boolean("bEnableVoiceChat", "启用语音聊天", True, "游戏功能"),
    boolean("bExistPlayerAfterLogout", "退出后保留角色", False, "游戏功能", "玩家退出后在原位置进入睡眠状态。"),
    boolean("bHardcore", "硬核模式", False, "游戏功能", "死亡后无法正常复活。"),
    boolean("bInvisibleOtherGuildBaseCampAreaFX", "隐藏其他公会基地边界", False, "游戏功能"),
    boolean("bIsPvP", "启用 PvP", False, "游戏功能"),
    boolean("bEnablePlayerToPlayerDamage", "允许玩家互相伤害", False, "游戏功能", "PvP 官方配套参数。"),
    boolean("bEnableDefenseOtherGuildPlayer", "基地防御其他公会玩家", False, "游戏功能", "PvP 官方配套参数。"),
    boolean("bIsRandomizerPalLevelRandom", "完全随机帕鲁等级", False, "游戏功能"),
    boolean("bIsStartLocationSelectByMap", "允许地图选择出生点", True, "游戏功能"),
    boolean("bShowPlayerList", "显示玩家列表", True, "游戏功能"),
    select("RandomizerType", "帕鲁随机模式", "None", ["None", "Region", "All"], "游戏功能"),
    text("RandomizerSeed", "随机模式种子", "", "游戏功能"),
    number("VoiceChatMaxVolumeDistance", "语音最大音量距离", 1500, "游戏功能", "此距离内语音不会衰减。", 0, 100000),
    number("VoiceChatZeroVolumeDistance", "语音静音距离", 15000, "游戏功能", "超过此距离听不到语音。", 0, 100000),

    # Game balance
    number("DayTimeSpeedRate", "白天速度倍率", 1.0, "游戏平衡", step=0.1, minimum=0.1, maximum=10),
    number("NightTimeSpeedRate", "夜晚速度倍率", 1.0, "游戏平衡", step=0.1, minimum=0.1, maximum=10),
    number("ExpRate", "经验倍率", 1.0, "游戏平衡", step=0.1, minimum=0.1, maximum=20),
    number("PalCaptureRate", "捕获概率倍率", 1.0, "游戏平衡", step=0.1, minimum=0.1, maximum=20),
    number("PalSpawnNumRate", "帕鲁生成倍率", 1.0, "游戏平衡", "较高数值会明显增加负载。", 0.1, 10, 0.1),
    number("PalDamageRateAttack", "帕鲁攻击倍率", 1.0, "游戏平衡", step=0.1, minimum=0.1, maximum=10),
    number("PalDamageRateDefense", "帕鲁承伤倍率", 1.0, "游戏平衡", step=0.1, minimum=0.1, maximum=10),
    number("PlayerDamageRateAttack", "玩家攻击倍率", 1.0, "游戏平衡", step=0.1, minimum=0.1, maximum=10),
    number("PlayerDamageRateDefense", "玩家承伤倍率", 1.0, "游戏平衡", step=0.1, minimum=0.1, maximum=10),
    number("PlayerStomachDecreaceRate", "玩家饥饿速度", 1.0, "游戏平衡", step=0.1, minimum=0.1, maximum=10),
    number("PlayerStaminaDecreaceRate", "玩家耐力消耗", 1.0, "游戏平衡", step=0.1, minimum=0.1, maximum=10),
    number("PlayerAutoHPRegeneRate", "玩家生命恢复", 1.0, "游戏平衡", step=0.1, minimum=0.1, maximum=10),
    number("PlayerAutoHpRegeneRateInSleep", "玩家睡眠恢复", 1.0, "游戏平衡", step=0.1, minimum=0.1, maximum=10),
    number("PalStomachDecreaceRate", "帕鲁饥饿速度", 1.0, "游戏平衡", step=0.1, minimum=0.1, maximum=10),
    number("PalStaminaDecreaceRate", "帕鲁耐力消耗", 1.0, "游戏平衡", step=0.1, minimum=0.1, maximum=10),
    number("PalAutoHPRegeneRate", "帕鲁生命恢复", 1.0, "游戏平衡", step=0.1, minimum=0.1, maximum=10),
    number("PalAutoHpRegeneRateInSleep", "帕鲁终端恢复", 1.0, "游戏平衡", step=0.1, minimum=0.1, maximum=10),
    number("BuildObjectDamageRate", "建筑承受伤害倍率", 1.0, "游戏平衡", step=0.1, minimum=0, maximum=10),
    number("BuildObjectDeteriorationDamageRate", "建筑劣化倍率", 1.0, "游戏平衡", step=0.1, minimum=0, maximum=10),
    number("CollectionDropRate", "采集掉落倍率", 1.0, "游戏平衡", step=0.1, minimum=0.1, maximum=20),
    number("CollectionObjectHpRate", "采集物生命倍率", 1.0, "游戏平衡", step=0.1, minimum=0.1, maximum=10),
    number("CollectionObjectRespawnSpeedRate", "采集物刷新间隔倍率", 1.0, "游戏平衡", step=0.1, minimum=0.1, maximum=10),
    number("EnemyDropItemRate", "敌人掉落倍率", 1.0, "游戏平衡", step=0.1, minimum=0.1, maximum=20),
    number("EquipmentDurabilityDamageRate", "装备耐久消耗倍率", 1.0, "游戏平衡", step=0.1, minimum=0, maximum=10),
    number("GuildPlayerMaxNum", "公会人数上限", 20, "游戏平衡", minimum=1, maximum=100),
    number("GuildRejoinCooldownMinutes", "重新加入公会冷却", 10, "游戏平衡", "单位：分钟。", 0, 10080),
    number("ItemCorruptionMultiplier", "物品腐坏倍率", 1.0, "游戏平衡", step=0.1, minimum=0, maximum=10),
    number("ItemWeightRate", "物品重量倍率", 1.0, "游戏平衡", step=0.1, minimum=0, maximum=10),
    number("MonsterFarmActionSpeedRate", "牧场生产速度", 1.0, "游戏平衡", step=0.1, minimum=0.1, maximum=10),
    number("PalEggDefaultHatchingTime", "巨大蛋孵化小时数", 72.0, "游戏平衡", minimum=0, maximum=1000, step=0.5),
    number("SupplyDropSpan", "陨石和补给间隔", 180, "游戏平衡", "单位：分钟。", 1, 10080),
    select("DeathPenalty", "死亡惩罚", "All", ["None", "Item", "ItemAndEquipment", "All"], "游戏平衡"),
    boolean("bPalLost", "死亡永久失去帕鲁", False, "游戏平衡"),
    number("BlockRespawnTime", "死亡重生冷却", 0, "游戏平衡", "单位：秒。", 0, 86400),
    number("RespawnPenaltyDurationThreshold", "重生惩罚生存阈值", 0, "游戏平衡", "单位：秒。", 0, 86400),
    number("RespawnPenaltyTimeScale", "重生冷却倍率", 1.0, "游戏平衡", minimum=0, maximum=100, step=0.1),
    boolean("bAdditionalDropItemWhenPlayerKillingInPvPMode", "PvP 击杀额外掉落", False, "游戏平衡"),
    text("AdditionalDropItemWhenPlayerKillingInPvPMode", "PvP 额外掉落物 ID", "", "游戏平衡"),
    number("AdditionalDropItemNumWhenPlayerKillingInPvPMode", "PvP 额外掉落数量", 1, "游戏平衡", minimum=0, maximum=999),
    text("DenyTechnologyList", "禁用科技 ID 列表", "", "游戏平衡", "使用官方 Technology ID 列表格式。"),
]


MINECRAFT_FIELDS = [
    text("motd", "服务器描述", "A cozy Minecraft server", "基础设置", "显示在多人服务器列表中的文字。"),
    number("max-players", "最大玩家数", 12, "基础设置", minimum=1, maximum=1000),
    select("gamemode", "默认游戏模式", "survival", ["survival", "creative", "adventure", "spectator"], "基础设置"),
    boolean("force-gamemode", "强制默认游戏模式", False, "基础设置"),
    select("difficulty", "游戏难度", "normal", ["peaceful", "easy", "normal", "hard"], "基础设置"),
    boolean("hardcore", "极限模式", False, "基础设置"),
    text("level-name", "世界目录名称", "world", "世界生成"),
    text("level-seed", "世界种子", "", "世界生成"),
    select("level-type", "世界类型", "minecraft:normal", ["minecraft:normal", "minecraft:flat", "minecraft:large_biomes", "minecraft:amplified", "minecraft:single_biome_surface"], "世界生成"),
    text("generator-settings", "生成器设置", "{}", "世界生成", "JSON 格式的自定义世界生成参数。"),
    boolean("generate-structures", "生成建筑结构", True, "世界生成"),
    number("max-world-size", "世界最大半径", 29999984, "世界生成", minimum=1, maximum=29999984),
    text("initial-enabled-packs", "初始启用数据包", "vanilla", "世界生成"),
    text("initial-disabled-packs", "初始禁用数据包", "", "世界生成"),
    number("server-port", "游戏端口", 25565, "网络与连接", minimum=1, maximum=65535),
    text("server-ip", "绑定 IP", "", "网络与连接", "通常留空以监听所有可用地址。"),
    boolean("online-mode", "正版验证", True, "网络与连接"),
    boolean("prevent-proxy-connections", "阻止代理连接", False, "网络与连接"),
    boolean("enable-status", "响应服务器列表查询", True, "网络与连接"),
    boolean("hide-online-players", "隐藏在线玩家列表", False, "网络与连接"),
    number("network-compression-threshold", "网络压缩阈值", 256, "网络与连接", "数据包达到该字节数后压缩；-1 禁用。", -1, 65535),
    number("rate-limit", "数据包速率限制", 0, "网络与连接", "0 表示不限制。", 0, 100000),
    boolean("use-native-transport", "使用原生网络传输", True, "网络与连接"),
    boolean("accepts-transfers", "接受服务器转移", False, "网络与连接"),
    boolean("enforce-secure-profile", "强制安全玩家档案", True, "网络与连接"),
    boolean("spawn-animals", "生成动物", True, "世界与玩法"),
    boolean("spawn-monsters", "生成怪物", True, "世界与玩法"),
    boolean("spawn-npcs", "生成村民", True, "世界与玩法"),
    boolean("allow-nether", "启用下界", True, "世界与玩法"),
    boolean("allow-flight", "允许飞行", False, "世界与玩法"),
    boolean("pvp", "启用 PvP", True, "世界与玩法"),
    number("spawn-protection", "出生点保护半径", 16, "世界与玩法", minimum=0, maximum=10000),
    number("player-idle-timeout", "玩家空闲踢出时间", 0, "世界与玩法", "单位：分钟；0 表示禁用。", 0, 10080),
    number("pause-when-empty-seconds", "空服暂停等待时间", 60, "世界与玩法", "无人在线多少秒后暂停世界；负数禁用。", -1, 86400),
    number("view-distance", "视距", 10, "性能", minimum=3, maximum=32),
    number("simulation-distance", "模拟距离", 10, "性能", minimum=3, maximum=32),
    number("entity-broadcast-range-percentage", "实体广播范围比例", 100, "性能", minimum=10, maximum=1000),
    number("max-tick-time", "单 Tick 最大耗时", 60000, "性能", "单位：毫秒；-1 禁用监控。", -1, 3600000),
    number("max-chained-neighbor-updates", "连锁方块更新上限", 1000000, "性能", minimum=-1, maximum=10000000),
    boolean("sync-chunk-writes", "同步写入区块", True, "性能"),
    select("region-file-compression", "区块压缩方式", "deflate", ["deflate", "lz4", "none"], "性能"),
    number("memory", "最大内存（GB）", 6, "Java 启动参数", "用于生成 -Xmx 参数，不属于 server.properties。", 1, 128),
    number("initial-memory", "初始内存（GB）", 2, "Java 启动参数", "用于生成 -Xms 参数。", 1, 128),
    boolean("nogui", "禁用服务端 GUI", True, "Java 启动参数"),
    boolean("enable-command-block", "启用命令方块", False, "管理与权限"),
    number("op-permission-level", "管理员权限等级", 4, "管理与权限", minimum=1, maximum=4),
    number("function-permission-level", "函数权限等级", 2, "管理与权限", minimum=1, maximum=4),
    boolean("white-list", "启用白名单", False, "管理与权限"),
    boolean("enforce-whitelist", "强制白名单", False, "管理与权限"),
    boolean("broadcast-console-to-ops", "向管理员广播控制台", True, "管理与权限"),
    boolean("broadcast-rcon-to-ops", "向管理员广播 RCON", True, "管理与权限"),
    boolean("enable-rcon", "启用 RCON", False, "远程接口"),
    number("rcon.port", "RCON 端口", 25575, "远程接口", minimum=1, maximum=65535),
    text("rcon.password", "RCON 密码", "", "远程接口", password=True),
    boolean("enable-query", "启用 GameSpy4 查询", False, "远程接口"),
    number("query.port", "查询端口", 25565, "远程接口", minimum=1, maximum=65535),
    boolean("enable-jmx-monitoring", "启用 JMX 监控", False, "远程接口"),
    text("resource-pack", "资源包 URL", "", "资源包"),
    text("resource-pack-id", "资源包 UUID", "", "资源包"),
    text("resource-pack-sha1", "资源包 SHA-1", "", "资源包"),
    text("resource-pack-prompt", "资源包提示文本", "", "资源包"),
    boolean("require-resource-pack", "强制使用资源包", False, "资源包"),
    text("bug-report-link", "问题反馈链接", "", "其他"),
    text("text-filtering-config", "文本过滤配置", "", "其他"),
    boolean("log-ips", "日志记录玩家 IP", True, "其他"),
]
